name: 构建项目

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag name'
        required: true

permissions:
  contents: write

jobs:

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: 安装环境
      uses: msys2/setup-msys2@v2
      with:
        install: git make mingw-w64-x86_64-gcc mingw-w64-x86_64-python mingw-w64-x86_64-lld mingw-w64-x86_64-llvm mingw-w64-x86_64-libc++

    - name: 签出源码
      uses: actions/checkout@v3

    - name: 编译项目
      env:
        MINGW64: "/mingw64"
        OVERRIDE_AR: "llvm-ar"
        OVERRIDE_CC: gcc
        OVERRIDE_CXX: g++
        ARCHOPTS: "-fomit-frame-pointer -fuse-ld=lld"
        SUBTARGET: neogeo
        SOURCES: "src/mame/neogeo"
        OPTIMIZE: 3
        DEPRECATED: 0
        NOWERROR: 1
        TOOLS: 1
        SEPARATE_BIN: 1
        PTR64: 1
        SYMBOLS: 1
        SYMLEVEL: 1
      run: |
        make -j9 && make -f dist.mak TARGET=neogeo

    - name: 上传资源
      uses: actions/upload-artifact@v3
      with:
        name: neogeo-windows
        path:  |
          ./build/release/x64/Release/neogeo/**/*
          ./artwork/**/*
          ./bgfx/**/*
          ./hlsl/**/*
          ./plugins/**/*
          ./samples/**/*

  publish:
    runs-on: ubuntu-latest
    needs: [ windows ]
    steps:
    - name: 下载资源
      uses: actions/download-artifact@v3
      with:
        name: neogeo-windows
        path: neogeo-windows/

    - name: 打包资源
      run: |
        cd neogeo-windows/ && tar cvfz ../neogeo_${{ github.event.inputs.tag_name }}.tgz ./ && cd -

    - name: 发布版本
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.tag_name }}
        name: server-v${{ github.event.inputs.tag_name }}
        body: v${{ github.event.inputs.tag_name }} 版本发布
        draft: false
        prerelease: false
        files: |
          neogeo_${{ github.event.inputs.tag_name }}.tgz
